/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    /**
     * Inscription
     * @description Crée un nouveau compte utilisateur. Le consentement RGPD est obligatoire.
     * Le rôle par défaut est CONSUMER si non spécifié.
     */
    post: operations["register"];
  };
  "/auth/login": {
    /**
     * Connexion
     * @description Connecte un utilisateur existant avec son email et mot de passe.
     * Retourne le jeton d'accès.
     */
    post: operations["login"];
  };
  "/auth/me": {
    /**
     * Profil courant
     * @description Récupère le profil de l'utilisateur authentifié.
     */
    get: operations["getMe"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      /** @example user-001 */
      id: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example Jean */
      first_name: string;
      /** @example Dupont */
      last_name: string;
      /**
       * @example CONSUMER
       * @enum {string}
       */
      role: "CONSUMER" | "PRODUCER" | "ADMIN";
      /** @example 33612345678 */
      phone?: string;
      /**
       * Format: uri
       * @example https://example.com/avatar.jpg
       */
      avatar_url?: string;
      /**
       * Format: date-time
       * @example "2025-04-01T10:00:00.000Z"
       */
      created_at: string;
    };
    Error: {
      /** @example Email manquant */
      error: string;
      /**
       * @example 400
       * @enum {integer}
       */
      status: 400 | 401 | 403 | 404 | 409 | 500;
      /**
       * @example {
       *   "field": "email",
       *   "message": "Email déjà utilisé"
       * }
       */
      details?: {
        [key: string]: unknown;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Inscription
   * @description Crée un nouveau compte utilisateur. Le consentement RGPD est obligatoire.
   * Le rôle par défaut est CONSUMER si non spécifié.
   */
  register: {
    requestBody: {
      content: {
        "application/json": {
          /**
           * Format: email
           * @example user@example.com
           */
          email: string;
          /** @example password123 */
          password: string;
          /** @example Jean */
          first_name: string;
          /** @example Dupont */
          last_name: string;
          /**
           * @example CONSUMER
           * @enum {string}
           */
          role?: "CONSUMER" | "PRODUCER";
          /** @example true */
          gdpr_consent: boolean;
        };
      };
    };
    responses: {
      /** @description Utilisateur créé avec succès */
      201: {
        content: {
          "application/json": {
            user: components["schemas"]["User"];
            /**
             * @description Token JWT pour l'authentification future
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
             */
            access_token: string;
          };
        };
      };
      /** @description Requête invalide (consentement RGPD manquant ou email déjà utilisé) */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Email déjà utilisé */
      409: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Erreur serveur */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Connexion
   * @description Connecte un utilisateur existant avec son email et mot de passe.
   * Retourne le jeton d'accès.
   */
  login: {
    requestBody: {
      content: {
        "application/json": {
          /**
           * Format: email
           * @example user@example.com
           */
          email: string;
          /** @example password123 */
          password: string;
        };
      };
    };
    responses: {
      /** @description Connexion réussie */
      200: {
        content: {
          "application/json": {
            user: components["schemas"]["User"];
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 */
            access_token: string;
          };
        };
      };
      /** @description Email ou mot de passe incorrect (ou compte inactive) */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Erreur serveur */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Profil courant
   * @description Récupère le profil de l'utilisateur authentifié.
   */
  getMe: {
    responses: {
      /** @description Profil de l'utilisateur */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Token manquant ou invalide */
      401: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Utilisateur introuvable */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Erreur serveur */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
