import type { Producer, Product, Message, ProductCategory } from '../models/types'

export interface SeedProducer extends Producer {
  first_name?: string
  last_name?: string
  rating?: number
  review_count?: number
  categories?: string[]
  is_open?: boolean
}

export interface SeedProduct extends Product {
  producer_name?: string
  is_bestseller?: boolean
  is_seasonal?: boolean
}

export interface SeedUser {
  id: string
  email: string
  password_hash: string
  first_name: string
  last_name: string
  role: 'CONSUMER' | 'PRODUCER' | 'ADMIN'
  phone?: string
  avatar_url?: string
  is_active: boolean
  gdpr_consent: boolean
  gdpr_consent_at?: string
  created_at: string
}

export interface SeedMessage extends Message {
  first_name?: string
  last_name?: string
}

export const seedProducers: SeedProducer[] = [
  {
    id: 'prod-001',
    user_id: 'user-producer-001',
    company_name: 'Ferme des Garrigues',
    description: 'Légumes bio et œufs fermiers — Une exploitation familiale au cœur du Pic Saint-Loup. Nous cultivons des variétés anciennes sans pesticides.',
    address: 'Route de Ganges, Saint-Gély-du-Fesc',
    city: 'Saint-Gély-du-Fesc',
    postal_code: '34980',
    latitude: 43.6938,
    longitude: 3.8049,
    website_url: 'https://ferme-garrigues.fr',
    banner_url: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000',
    is_verified: true,
    created_at: '2025-01-15T10:00:00Z',
    first_name: 'Marie',
    last_name: 'Martin',
    rating: 4.8,
    review_count: 120,
    categories: ['Légumes', 'Œufs'],
    is_open: true,
  },
  {
    id: 'prod-002',
    user_id: 'user-prod-002',
    company_name: 'Mas des Coquillages',
    description: "Huîtres et moules de Bouzigues — Dégustez le meilleur de l'étang de Thau. Producteurs d'huîtres de père en fils depuis 1950.",
    address: 'Port de pêche, Bouzigues',
    city: 'Bouzigues',
    postal_code: '34140',
    latitude: 43.4475,
    longitude: 3.6583,
    website_url: 'https://mas-coquillages.fr',
    banner_url: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?q=80&w=1000',
    is_verified: true,
    created_at: '2025-01-20T08:30:00Z',
    first_name: 'Jean-Pierre',
    last_name: 'Martinez',
    rating: 4.9,
    review_count: 340,
    categories: ['Poissons & Crustacés'],
    is_open: true,
  },
  {
    id: 'prod-003',
    user_id: 'user-prod-003',
    company_name: "Domaine de l'Oliveraie",
    description: "Huile d'olive et Lucques du Languedoc — Pressage à froid et récolte manuelle. Découvrez notre huile d'olive vierge extra médaillée.",
    address: "Chemin des Oliviers, Saint-Jean-de-Védas",
    city: 'Saint-Jean-de-Védas',
    postal_code: '34430',
    latitude: 43.5771,
    longitude: 3.8258,
    website_url: 'https://domaine-oliveraie.fr',
    banner_url: 'https://images.unsplash.com/photo-1445296115253-ad62c721b315?q=80&w=1000',
    is_verified: true,
    created_at: '2025-02-01T09:00:00Z',
    first_name: 'Olivier',
    last_name: 'Dubois',
    rating: 4.7,
    review_count: 95,
    categories: ['Épicerie', 'Huile'],
    is_open: true,
  },
  {
    id: 'prod-004',
    user_id: 'user-prod-004',
    company_name: "Château de l'Engarran",
    description: 'Vins AOC Languedoc & Grés de Montpellier — Domaine viticole historique. Vins bios élégants et balades dans les jardins à la française.',
    address: 'Route de Lavérune, Lavérune',
    city: 'Lavérune',
    postal_code: '34880',
    latitude: 43.5962,
    longitude: 3.8021,
    website_url: 'https://chateau-engarran.fr',
    banner_url: 'https://images.unsplash.com/photo-1504279577054-acfeccf8fc52?q=80&w=1000',
    is_verified: true,
    created_at: '2025-02-05T11:00:00Z',
    first_name: 'Philippe',
    last_name: 'Laurent',
    rating: 4.9,
    review_count: 156,
    categories: ['Vins', 'Spiritueux'],
    is_open: true,
  },
  {
    id: 'prod-005',
    user_id: 'user-prod-005',
    company_name: 'Le Rucher du Pic',
    description: 'Miels de garrigue et gelée royale — Apiculture transhumante respectueuse des abeilles. Miel de thym, romarin et châtaignier.',
    address: "Hameau de l'Hortus, Valflaunès",
    city: 'Valflaunès',
    postal_code: '34560',
    latitude: 43.8014,
    longitude: 3.8719,
    banner_url: 'https://images.unsplash.com/photo-1473973266408-ed4e27abdd47?q=80&w=1000',
    is_verified: true,
    created_at: '2025-02-10T14:00:00Z',
    first_name: 'Thomas',
    last_name: 'Lefèvre',
    rating: 4.8,
    review_count: 67,
    categories: ['Miel', 'Épicerie'],
    is_open: false,
  },
  {
    id: 'prod-006',
    user_id: 'user-prod-006',
    company_name: 'La Chèvrerie du Mas Rolland',
    description: 'Pélardons AOP et fromages frais — Au pied du Larzac, nos chèvres pâturent en pleine liberté. Fabrication traditionnelle de Pélardons au lait cru.',
    address: 'Chemin du Mas, Montesquieu',
    city: 'Montesquieu',
    postal_code: '34120',
    latitude: 43.5611,
    longitude: 3.2755,
    website_url: 'https://chevrerie-rolland.fr',
    banner_url: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?q=80&w=1000',
    is_verified: true,
    created_at: '2025-02-14T10:00:00Z',
    first_name: 'Isabelle',
    last_name: 'Rolland',
    rating: 4.9,
    review_count: 88,
    categories: ['Fromage', 'Crèmerie'],
    is_open: true,
  },
  {
    id: 'prod-007',
    user_id: 'user-prod-007',
    company_name: 'Les Vergers du Jaur',
    description: "Cerises, châtaignes et jus de fruits — Spécialiste des fruits de montagne et de la châtaigne d'Olargues. Tout est transformé à la ferme.",
    address: 'Le Village, Olargues',
    city: 'Olargues',
    postal_code: '34360',
    latitude: 43.5575,
    longitude: 2.9125,
    banner_url: 'https://images.unsplash.com/photo-1464618663641-bbdd760ae84a?q=80&w=1000',
    is_verified: true,
    created_at: '2025-02-18T08:00:00Z',
    first_name: 'François',
    last_name: 'Jaurès',
    rating: 4.6,
    review_count: 42,
    categories: ['Fruits', 'Boissons'],
    is_open: true,
  },
  {
    id: 'prod-008',
    user_id: 'user-prod-008',
    company_name: 'Rizière de la Marette',
    description: "Riz de Camargue et taureau — Situé aux portes de la Grande-Motte, nous produisons un riz d'exception en zone Natura 2000.",
    address: "Route de l'Espiguette, Le Grau-du-Roi",
    city: 'Le Grau-du-Roi',
    postal_code: '30240',
    latitude: 43.5358,
    longitude: 4.1352,
    website_url: 'https://riziere-marette.fr',
    banner_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000',
    is_verified: true,
    created_at: '2025-02-22T09:30:00Z',
    first_name: 'Ahmed',
    last_name: 'Benali',
    rating: 4.7,
    review_count: 112,
    categories: ['Épicerie', 'Viande'],
    is_open: true,
  },
  {
    id: 'prod-009',
    user_id: 'user-prod-009',
    company_name: 'Brasserie Alaryk',
    description: 'Bières artisanales bio de Béziers — Bières de haute qualité, brassées sans additifs ni conservateurs. Un savoir-faire biterrois reconnu.',
    address: "Rue de l'Industrie, Béziers",
    city: 'Béziers',
    postal_code: '34500',
    latitude: 43.3442,
    longitude: 3.2158,
    website_url: 'https://brasserie-alaryk.fr',
    banner_url: 'https://images.unsplash.com/photo-1571767454098-246b9198573e?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-01T12:00:00Z',
    first_name: 'Luc',
    last_name: 'Alary',
    rating: 4.8,
    review_count: 195,
    categories: ['Boissons'],
    is_open: true,
  },
  {
    id: 'prod-010',
    user_id: 'user-prod-010',
    company_name: 'Maraîcher du Lac',
    description: 'Melons et fraises du Salagou — Sur les terres rouges (ruffes) du lac du Salagou, nos fruits regorgent de sucre et de soleil.',
    address: "Les Terrasses, Clermont-l'Hérault",
    city: "Clermont-l'Hérault",
    postal_code: '34800',
    latitude: 43.6278,
    longitude: 3.3964,
    banner_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-05T07:00:00Z',
    first_name: 'Émile',
    last_name: 'Lacoste',
    rating: 4.9,
    review_count: 76,
    categories: ['Fruits', 'Légumes'],
    is_open: true,
  },
  {
    id: 'prod-011',
    user_id: 'user-prod-011',
    company_name: "Le Mas de l'Ecluze",
    description: 'Asperges des sables et petits pois — Culture traditionnelle en pleine terre dans les sables de Lansargues. Une saveur unique grâce à notre terroir littoral.',
    address: "Chemin de l'Ecluze, Lansargues",
    city: 'Lansargues',
    postal_code: '34130',
    latitude: 43.6525,
    longitude: 4.0728,
    banner_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-08T10:00:00Z',
    first_name: 'Claire',
    last_name: 'Martin',
    rating: 4.8,
    review_count: 54,
    categories: ['Légumes'],
    is_open: true,
  },
  {
    id: 'prod-012',
    user_id: 'user-prod-012',
    company_name: 'Pêcherie de la Méditerranée',
    description: 'Poisson bleu et friture du Golfe — Pêche artisanale au départ de Palavas-les-Flots. Daurades, loups et rougets selon arrivage du matin.',
    address: 'Quai Paul Cunq, Palavas-les-Flots',
    city: 'Palavas-les-Flots',
    postal_code: '34250',
    latitude: 43.5275,
    longitude: 3.9314,
    website_url: 'https://pecherie-mediterranee.fr',
    banner_url: 'https://images.unsplash.com/photo-1498654077810-12c21d4d6dc3?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-10T06:00:00Z',
    first_name: 'Sofia',
    last_name: 'Costa',
    rating: 4.9,
    review_count: 215,
    categories: ['Poissons & Crustacés'],
    is_open: true,
  },
  {
    id: 'prod-013',
    user_id: 'user-prod-013',
    company_name: "L'Escargot du Pic",
    description: "Héliciculture artisanale — Élevage de Gros Gris en plein air au pied de l'Hortus. Produits transformés sans conservateurs.",
    address: 'Route de Ganges, Saint-Mathieu-de-Tréviers',
    city: 'Saint-Mathieu-de-Tréviers',
    postal_code: '34270',
    latitude: 43.7694,
    longitude: 3.8681,
    banner_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-12T11:00:00Z',
    first_name: 'Marcel',
    last_name: 'Petit',
    rating: 4.7,
    review_count: 38,
    categories: ['Épicerie', 'Viande'],
    is_open: true,
  },
  {
    id: 'prod-014',
    user_id: 'user-prod-014',
    company_name: "Spiruline de l'Hérault",
    description: 'Super-aliment produit localement — Culture écologique de spiruline artisanale sous serre. Riche en fer et vitamines, 100% naturelle.',
    address: 'Lieu-dit La Plaine, Gignac',
    city: 'Gignac',
    postal_code: '34150',
    latitude: 43.6521,
    longitude: 3.5512,
    website_url: 'https://spiruline-herault.fr',
    banner_url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-15T09:00:00Z',
    first_name: 'Nadine',
    last_name: 'Blanc',
    rating: 4.9,
    review_count: 29,
    categories: ['Épicerie'],
    is_open: true,
  },
  {
    id: 'prod-015',
    user_id: 'user-prod-015',
    company_name: 'Boucherie des Terroirs',
    description: "Agneau de l'Hérault et veau d'Aveyron — Sélection rigoureuse de viandes locales. Nous travaillons avec des éleveurs respectueux du bien-être animal.",
    address: 'Avenue de Toulouse, Montpellier',
    city: 'Montpellier',
    postal_code: '34000',
    latitude: 43.5982,
    longitude: 3.8642,
    website_url: 'https://boucherie-terroirs.fr',
    banner_url: 'https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-18T08:00:00Z',
    first_name: 'André',
    last_name: 'Moreau',
    rating: 4.8,
    review_count: 142,
    categories: ['Viande'],
    is_open: true,
  },
  {
    id: 'prod-016',
    user_id: 'user-prod-016',
    company_name: 'Safran du Languedoc',
    description: "L'or rouge de nos garrigues — Safran pur en stigmates. Culture artisanale sur les hauteurs de Murviel-lès-Montpellier.",
    address: 'Chemin de la Coste, Murviel-lès-Montpellier',
    city: 'Murviel-lès-Montpellier',
    postal_code: '34570',
    latitude: 43.6041,
    longitude: 3.7383,
    website_url: 'https://safran-languedoc.fr',
    banner_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-20T14:00:00Z',
    first_name: 'Catherine',
    last_name: 'Roux',
    rating: 5.0,
    review_count: 24,
    categories: ['Épicerie'],
    is_open: false,
  },
  {
    id: 'prod-017',
    user_id: 'user-prod-017',
    company_name: "La Ferme de l'Orque",
    description: 'Lait de vache et yaourts fermiers — Une des dernières laiteries de plaine. Fromages blancs, yaourts onctueux et lait frais chaque jour.',
    address: 'Route de Pérols, Lattes',
    city: 'Lattes',
    postal_code: '34970',
    latitude: 43.5678,
    longitude: 3.9025,
    banner_url: 'https://images.unsplash.com/photo-1488459739732-26d36275dbe7?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-22T10:00:00Z',
    first_name: 'Paul',
    last_name: 'Faure',
    rating: 4.7,
    review_count: 91,
    categories: ['Crèmerie'],
    is_open: true,
  },
  {
    id: 'prod-018',
    user_id: 'user-prod-018',
    company_name: 'Pépinière des Arômes',
    description: 'Herbes aromatiques et plantes à tisanes — Plus de 50 variétés de plantes aromatiques bios. Fraîches ou séchées pour vos cuisines.',
    address: 'Route de Sète, Vic-la-Gardiole',
    city: 'Vic-la-Gardiole',
    postal_code: '34110',
    latitude: 43.4902,
    longitude: 3.7961,
    website_url: 'https://pepiniere-aromes.fr',
    banner_url: 'https://images.unsplash.com/photo-1523348830342-d0187cf0c28d?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-25T09:00:00Z',
    first_name: 'Véronique',
    last_name: 'Girard',
    rating: 4.6,
    review_count: 45,
    categories: ['Épicerie', 'Légumes'],
    is_open: true,
  },
  {
    id: 'prod-019',
    user_id: 'user-prod-019',
    company_name: 'Domaine du Météore',
    description: "Vins nés d'un cratère d'impact — Vignoble insolite situé dans un cratère de météorite à Faugères. Vins en biodynamie.",
    address: 'Le Village, Cabrerolles',
    city: 'Cabrerolles',
    postal_code: '34480',
    latitude: 43.5414,
    longitude: 3.1258,
    website_url: 'https://domaine-meteore.fr',
    banner_url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b0ca7df?q=80&w=1000',
    is_verified: true,
    created_at: '2025-03-28T11:00:00Z',
    first_name: 'Céline',
    last_name: 'Morel',
    rating: 4.9,
    review_count: 178,
    categories: ['Vins'],
    is_open: true,
  },
  {
    id: 'prod-020',
    user_id: 'user-prod-020',
    company_name: 'Confiserie du Languedoc',
    description: 'Grisettes de Montpellier et Berlingots — Artisan confiseur perpétuant la tradition des Grisettes au miel et à la réglisse depuis 1837.',
    address: "Rue de l'Aiguillerie, Montpellier",
    city: 'Montpellier',
    postal_code: '34000',
    latitude: 43.6125,
    longitude: 3.8785,
    website_url: 'https://confiserie-languedoc.fr',
    banner_url: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?q=80&w=1000',
    is_verified: true,
    created_at: '2025-04-01T10:00:00Z',
    first_name: 'Henri',
    last_name: 'Lambert',
    rating: 4.8,
    review_count: 312,
    categories: ['Épicerie'],
    is_open: true,
  },
]

export const seedProducts: SeedProduct[] = [
  {
    id: 'sku-001',
    producer_id: 'prod-001',
    name: 'Tomates Anciennes',
    description: 'Variétés anciennes cultivées en plein champ, goût authentique et parfumé.',
    price: 4.50,
    stock: 50,
    unit: 'kg',
    category: 'FRUITS_VEGETABLES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1592394933325-10eb4440533b?q=80&w=600',
    is_available: true,
    created_at: '2025-04-01T08:00:00Z',
    producer_name: 'Ferme des Garrigues',
    is_seasonal: true,
  },
  {
    id: 'sku-002',
    producer_id: 'prod-001',
    name: 'Jeunes Pousses',
    description: 'Mélange de jeunes pousses de salade, fraîches et croquantes.',
    price: 3.25,
    stock: 35,
    unit: '300g',
    category: 'FRUITS_VEGETABLES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1582515073490-39981397c445?q=80&w=600',
    is_available: true,
    created_at: '2025-04-01T08:10:00Z',
    producer_name: 'Ferme des Garrigues',
  },
  {
    id: 'sku-003',
    producer_id: 'prod-001',
    name: 'Œufs Plein Air',
    description: 'Œufs de poules élevées en plein air, frais du jour.',
    price: 6.50,
    stock: 25,
    unit: 'boîte de 12',
    category: 'DAIRY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1582722134903-b12ee9479b7b?q=80&w=600',
    is_available: true,
    created_at: '2025-04-01T08:20:00Z',
    producer_name: 'Ferme des Garrigues',
  },
  {
    id: 'sku-004',
    producer_id: 'prod-002',
    name: 'Huîtres N°3 (Spéciales)',
    description: "Huîtres spéciales de l'étang de Thau, charnues et iodées.",
    price: 14.00,
    stock: 40,
    unit: 'douzaine',
    category: 'MEAT' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1599458352231-039779354366?q=80&w=600',
    is_available: true,
    created_at: '2025-04-02T07:00:00Z',
    producer_name: 'Mas des Coquillages',
    is_bestseller: true,
  },
  {
    id: 'sku-005',
    producer_id: 'prod-002',
    name: "Moules de l'Étang",
    description: "Moules fraîches de l'étang de Thau, idéales en marinière.",
    price: 6.50,
    stock: 30,
    unit: 'kg',
    category: 'MEAT' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=600',
    is_available: true,
    created_at: '2025-04-02T07:10:00Z',
    producer_name: 'Mas des Coquillages',
  },
  {
    id: 'sku-006',
    producer_id: 'prod-003',
    name: "Huile d'Olive Vierge Extra",
    description: "Huile d'olive vierge extra pressée à froid, fruitée et médaille d'or.",
    price: 18.50,
    stock: 20,
    unit: '75cl',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=600',
    is_available: true,
    created_at: '2025-04-03T09:00:00Z',
    producer_name: "Domaine de l'Oliveraie",
  },
  {
    id: 'sku-007',
    producer_id: 'prod-003',
    name: 'Olives Lucques du Languedoc',
    description: 'Olives Lucques vertes, charnues et fondantes, variété emblématique du Languedoc.',
    price: 5.80,
    stock: 40,
    unit: '250g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1563823251941-b9989d1e8d97?q=80&w=600',
    is_available: true,
    created_at: '2025-04-03T09:10:00Z',
    producer_name: "Domaine de l'Oliveraie",
  },
  {
    id: 'sku-008',
    producer_id: 'prod-004',
    name: 'AOP Grés de Montpellier (Rouge)',
    description: 'Vin rouge AOC élégant, notes de garrigue et de fruits noirs.',
    price: 15.00,
    stock: 60,
    unit: 'bouteille',
    category: 'BEVERAGES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=600',
    is_available: true,
    created_at: '2025-04-04T10:00:00Z',
    producer_name: "Château de l'Engarran",
  },
  {
    id: 'sku-009',
    producer_id: 'prod-004',
    name: 'Languedoc Rosé Bio',
    description: 'Rosé biologique frais et fruité, parfait pour l\'été.',
    price: 11.50,
    stock: 45,
    unit: 'bouteille',
    category: 'BEVERAGES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?q=80&w=600',
    is_available: true,
    created_at: '2025-04-04T10:10:00Z',
    producer_name: "Château de l'Engarran",
    is_seasonal: true,
  },
  {
    id: 'sku-010',
    producer_id: 'prod-005',
    name: 'Miel de Garrigue',
    description: 'Miel toutes fleurs de garrigue, récolté en transhumance.',
    price: 12.00,
    stock: 30,
    unit: '500g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1587049633562-ad3002f38b2c?q=80&w=600',
    is_available: true,
    created_at: '2025-04-05T08:00:00Z',
    producer_name: 'Le Rucher du Pic',
    is_bestseller: true,
  },
  {
    id: 'sku-011',
    producer_id: 'prod-005',
    name: 'Gelée Royale Fraîche',
    description: 'Gelée royale fraîche récoltée artisanalement, riche en vitamines.',
    price: 22.00,
    stock: 15,
    unit: '20g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1471943311424-646960669fba?q=80&w=600',
    is_available: true,
    created_at: '2025-04-05T08:10:00Z',
    producer_name: 'Le Rucher du Pic',
  },
  {
    id: 'sku-012',
    producer_id: 'prod-006',
    name: 'Pélardon AOP',
    description: 'Fromage de chèvre AOP au lait cru, affiné traditionnellement.',
    price: 2.80,
    stock: 50,
    unit: 'pièce',
    category: 'DAIRY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1485962391945-424236402025?q=80&w=600',
    is_available: true,
    created_at: '2025-04-06T09:00:00Z',
    producer_name: 'La Chèvrerie du Mas Rolland',
    is_bestseller: true,
  },
  {
    id: 'sku-013',
    producer_id: 'prod-006',
    name: 'Faisselle de chèvre',
    description: 'Faisselle onctueuse de chèvre, fraîche et légère.',
    price: 4.20,
    stock: 25,
    unit: '4 pots',
    category: 'DAIRY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?q=80&w=600',
    is_available: true,
    created_at: '2025-04-06T09:10:00Z',
    producer_name: 'La Chèvrerie du Mas Rolland',
  },
  {
    id: 'sku-014',
    producer_id: 'prod-007',
    name: 'Jus de Pomme Trouble',
    description: 'Jus de pomme non filtré, pressé à la ferme.',
    price: 4.50,
    stock: 40,
    unit: '1L',
    category: 'BEVERAGES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1568909344668-6f14a07b56a0?q=80&w=600',
    is_available: true,
    created_at: '2025-04-07T08:00:00Z',
    producer_name: 'Les Vergers du Jaur',
  },
  {
    id: 'sku-015',
    producer_id: 'prod-007',
    name: 'Crème de Châtaigne',
    description: 'Crème onctueuse de châtaignes d\'Olargues, sans additifs.',
    price: 6.90,
    stock: 35,
    unit: '370g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1590401443227-aa7df56d787a?q=80&w=600',
    is_available: true,
    created_at: '2025-04-07T08:10:00Z',
    producer_name: 'Les Vergers du Jaur',
  },
  {
    id: 'sku-016',
    producer_id: 'prod-008',
    name: 'Riz Rouge de Camargue',
    description: 'Riz rouge complet de Camargue, culture respectueuse Natura 2000.',
    price: 5.20,
    stock: 45,
    unit: '500g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=600',
    is_available: true,
    created_at: '2025-04-08T07:00:00Z',
    producer_name: 'Rizière de la Marette',
  },
  {
    id: 'sku-017',
    producer_id: 'prod-008',
    name: 'Saucisson de Taureau',
    description: 'Saucisson sec de taureau de Camargue, saveur intense.',
    price: 8.50,
    stock: 30,
    unit: 'pièce',
    category: 'MEAT' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1544124499-58912cbddaad?q=80&w=600',
    is_available: true,
    created_at: '2025-04-08T07:10:00Z',
    producer_name: 'Rizière de la Marette',
  },
  {
    id: 'sku-018',
    producer_id: 'prod-009',
    name: 'Alaryk Blonde Bio',
    description: 'Bière blonde artisanale bio, houblon et malt locaux.',
    price: 3.50,
    stock: 80,
    unit: '33cl',
    category: 'BEVERAGES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?q=80&w=600',
    is_available: true,
    created_at: '2025-04-09T10:00:00Z',
    producer_name: 'Brasserie Alaryk',
  },
  {
    id: 'sku-019',
    producer_id: 'prod-009',
    name: 'Coffret Dégustation (6 bières)',
    description: 'Coffret de 6 bières artisanales variées pour découvrir la gamme.',
    price: 19.90,
    stock: 20,
    unit: 'pack',
    category: 'BEVERAGES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=600',
    is_available: true,
    created_at: '2025-04-09T10:10:00Z',
    producer_name: 'Brasserie Alaryk',
  },
  {
    id: 'sku-020',
    producer_id: 'prod-010',
    name: 'Melon de Clermont',
    description: 'Melon Charentais cultivé sur les ruffes du Salagou, sucré et parfumé.',
    price: 3.50,
    stock: 40,
    unit: 'pièce',
    category: 'FRUITS_VEGETABLES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1571575173700-afb9492e6a50?q=80&w=600',
    is_available: true,
    created_at: '2025-04-10T07:00:00Z',
    producer_name: 'Maraîcher du Lac',
    is_seasonal: true,
  },
  {
    id: 'sku-021',
    producer_id: 'prod-010',
    name: 'Fraises Gariguette',
    description: 'Fraises Gariguette de plein champ, rouges et juteuses.',
    price: 5.90,
    stock: 25,
    unit: '250g',
    category: 'FRUITS_VEGETABLES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1464960350473-ab74ed46589a?q=80&w=600',
    is_available: true,
    created_at: '2025-04-10T07:10:00Z',
    producer_name: 'Maraîcher du Lac',
    is_seasonal: true,
  },
  {
    id: 'sku-022',
    producer_id: 'prod-011',
    name: 'Asperges Vertes',
    description: 'Asperges vertes des sables de Lansargues, tendres et parfumées.',
    price: 7.50,
    stock: 30,
    unit: 'botte',
    category: 'FRUITS_VEGETABLES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1515471204579-f30b050d0354?q=80&w=600',
    is_available: true,
    created_at: '2025-04-11T08:00:00Z',
    producer_name: "Le Mas de l'Ecluze",
    is_seasonal: true,
  },
  {
    id: 'sku-023',
    producer_id: 'prod-012',
    name: 'Daurade Royale',
    description: 'Daurade royale pêchée dans le Golfe du Lion, extra fraîche.',
    price: 24.00,
    stock: 15,
    unit: 'kg',
    category: 'MEAT' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1534948664780-609f7a474708?q=80&w=600',
    is_available: true,
    created_at: '2025-04-12T06:00:00Z',
    producer_name: 'Pêcherie de la Méditerranée',
  },
  {
    id: 'sku-024',
    producer_id: 'prod-013',
    name: 'Escargots à la Biterroise',
    description: 'Gros Gris de l\'Hortus, préparés à la biterroise sans conservateurs.',
    price: 12.50,
    stock: 20,
    unit: 'douzaine',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?q=80&w=600',
    is_available: true,
    created_at: '2025-04-13T09:00:00Z',
    producer_name: "L'Escargot du Pic",
  },
  {
    id: 'sku-025',
    producer_id: 'prod-014',
    name: 'Spiruline en Paillettes',
    description: 'Spiruline artisanale en paillettes, riche en fer et protéines.',
    price: 15.00,
    stock: 25,
    unit: '100g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1614859132130-142c11438992?q=80&w=600',
    is_available: true,
    created_at: '2025-04-14T10:00:00Z',
    producer_name: "Spiruline de l'Hérault",
  },
  {
    id: 'sku-026',
    producer_id: 'prod-015',
    name: 'Côte de Veau',
    description: "Côte de veau d'Aveyron, élevage respectueux et bien-être animal.",
    price: 28.90,
    stock: 10,
    unit: 'kg',
    category: 'MEAT' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?q=80&w=600',
    is_available: true,
    created_at: '2025-04-15T08:00:00Z',
    producer_name: 'Boucherie des Terroirs',
  },
  {
    id: 'sku-027',
    producer_id: 'prod-016',
    name: 'Stigmates de Safran',
    description: 'Safran pur en stigmates, récolté et séché à la main.',
    price: 32.00,
    stock: 8,
    unit: '1g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1615485247078-47aa404899da?q=80&w=600',
    is_available: true,
    created_at: '2025-04-16T14:00:00Z',
    producer_name: 'Safran du Languedoc',
  },
  {
    id: 'sku-028',
    producer_id: 'prod-017',
    name: 'Yaourt Nature x4',
    description: 'Yaourts fermiers nature au lait de vache, onctueux et crémeux.',
    price: 3.80,
    stock: 40,
    unit: 'pack',
    category: 'DAIRY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1488470039733-573b5270227c?q=80&w=600',
    is_available: true,
    created_at: '2025-04-17T09:00:00Z',
    producer_name: "La Ferme de l'Orque",
  },
  {
    id: 'sku-029',
    producer_id: 'prod-018',
    name: 'Basilic Grand Vert',
    description: 'Plante aromatique bio, basilic grand vert frais en pot.',
    price: 2.50,
    stock: 50,
    unit: 'pot',
    category: 'FRUITS_VEGETABLES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?q=80&w=600',
    is_available: true,
    created_at: '2025-04-18T08:00:00Z',
    producer_name: 'Pépinière des Arômes',
  },
  {
    id: 'sku-030',
    producer_id: 'prod-019',
    name: 'Faugères "Les Léonides"',
    description: 'Vin rouge de Faugères en biodynamie, terroir de cratère.',
    price: 18.00,
    stock: 35,
    unit: 'bouteille',
    category: 'BEVERAGES' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=600',
    is_available: true,
    created_at: '2025-04-19T11:00:00Z',
    producer_name: 'Domaine du Météore',
  },
  {
    id: 'sku-031',
    producer_id: 'prod-020',
    name: 'Grisettes de Montpellier',
    description: 'Bonbons Grisettes au miel et à la réglisse, recette depuis 1837.',
    price: 6.50,
    stock: 45,
    unit: '150g',
    category: 'FINE_GROCERY' as ProductCategory,
    image_url: 'https://images.unsplash.com/photo-1582043242136-213028d7088f?q=80&w=600',
    is_available: true,
    created_at: '2025-04-20T10:00:00Z',
    producer_name: 'Confiserie du Languedoc',
    is_bestseller: true,
  },
]

export const seedUsers: SeedUser[] = [
  {
    id: 'user-consumer-001',
    email: 'jean@exemple.com',
    password_hash: '',
    first_name: 'Jean',
    last_name: 'Dupont',
    role: 'CONSUMER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-01-01T00:00:00Z',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-producer-001',
    email: 'ferme@exemple.com',
    password_hash: '',
    first_name: 'Marie',
    last_name: 'Martin',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-01-15T10:00:00Z',
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'user-prod-002',
    email: 'jp.martinez@bouzigues.fr',
    password_hash: '',
    first_name: 'Jean-Pierre',
    last_name: 'Martinez',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-01-20T08:30:00Z',
    created_at: '2025-01-20T08:30:00Z',
  },
  {
    id: 'user-prod-003',
    email: 'olivier.dubois@oliveraie.fr',
    password_hash: '',
    first_name: 'Olivier',
    last_name: 'Dubois',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-02-01T09:00:00Z',
    created_at: '2025-02-01T09:00:00Z',
  },
  {
    id: 'user-prod-004',
    email: 'philippe@engarran.fr',
    password_hash: '',
    first_name: 'Philippe',
    last_name: 'Laurent',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-02-05T11:00:00Z',
    created_at: '2025-02-05T11:00:00Z',
  },
  {
    id: 'user-prod-005',
    email: 'thomas@rucher-pic.fr',
    password_hash: '',
    first_name: 'Thomas',
    last_name: 'Lefèvre',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-02-10T14:00:00Z',
    created_at: '2025-02-10T14:00:00Z',
  },
  {
    id: 'user-prod-006',
    email: 'isabelle@chevrerie.fr',
    password_hash: '',
    first_name: 'Isabelle',
    last_name: 'Rolland',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-02-14T10:00:00Z',
    created_at: '2025-02-14T10:00:00Z',
  },
  {
    id: 'user-prod-007',
    email: 'francois@vergers-jaur.fr',
    password_hash: '',
    first_name: 'François',
    last_name: 'Jaurès',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-02-18T08:00:00Z',
    created_at: '2025-02-18T08:00:00Z',
  },
  {
    id: 'user-prod-008',
    email: 'ahmed@riziere.fr',
    password_hash: '',
    first_name: 'Ahmed',
    last_name: 'Benali',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-02-22T09:30:00Z',
    created_at: '2025-02-22T09:30:00Z',
  },
  {
    id: 'user-prod-009',
    email: 'luc@alaryk.fr',
    password_hash: '',
    first_name: 'Luc',
    last_name: 'Alary',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-01T12:00:00Z',
    created_at: '2025-03-01T12:00:00Z',
  },
  {
    id: 'user-prod-010',
    email: 'emile@maraicher-lac.fr',
    password_hash: '',
    first_name: 'Émile',
    last_name: 'Lacoste',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-05T07:00:00Z',
    created_at: '2025-03-05T07:00:00Z',
  },
  {
    id: 'user-prod-011',
    email: 'claire@mas-ecluze.fr',
    password_hash: '',
    first_name: 'Claire',
    last_name: 'Martin',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-08T10:00:00Z',
    created_at: '2025-03-08T10:00:00Z',
  },
  {
    id: 'user-prod-012',
    email: 'sofia@pecherie.fr',
    password_hash: '',
    first_name: 'Sofia',
    last_name: 'Costa',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-10T06:00:00Z',
    created_at: '2025-03-10T06:00:00Z',
  },
  {
    id: 'user-prod-013',
    email: 'marcel@escargot-pic.fr',
    password_hash: '',
    first_name: 'Marcel',
    last_name: 'Petit',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-12T11:00:00Z',
    created_at: '2025-03-12T11:00:00Z',
  },
  {
    id: 'user-prod-014',
    email: 'nadine@spiruline.fr',
    password_hash: '',
    first_name: 'Nadine',
    last_name: 'Blanc',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-15T09:00:00Z',
    created_at: '2025-03-15T09:00:00Z',
  },
  {
    id: 'user-prod-015',
    email: 'andre@boucherie-terroirs.fr',
    password_hash: '',
    first_name: 'André',
    last_name: 'Moreau',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-18T08:00:00Z',
    created_at: '2025-03-18T08:00:00Z',
  },
  {
    id: 'user-prod-016',
    email: 'catherine@safran-languedoc.fr',
    password_hash: '',
    first_name: 'Catherine',
    last_name: 'Roux',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-20T14:00:00Z',
    created_at: '2025-03-20T14:00:00Z',
  },
  {
    id: 'user-prod-017',
    email: 'paul@ferme-orque.fr',
    password_hash: '',
    first_name: 'Paul',
    last_name: 'Faure',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-22T10:00:00Z',
    created_at: '2025-03-22T10:00:00Z',
  },
  {
    id: 'user-prod-018',
    email: 'veronique@pepiniere-aromes.fr',
    password_hash: '',
    first_name: 'Véronique',
    last_name: 'Girard',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-25T09:00:00Z',
    created_at: '2025-03-25T09:00:00Z',
  },
  {
    id: 'user-prod-019',
    email: 'celine@domaine-meteore.fr',
    password_hash: '',
    first_name: 'Céline',
    last_name: 'Morel',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-03-28T11:00:00Z',
    created_at: '2025-03-28T11:00:00Z',
  },
  {
    id: 'user-prod-020',
    email: 'henri@confiserie-languedoc.fr',
    password_hash: '',
    first_name: 'Henri',
    last_name: 'Lambert',
    role: 'PRODUCER',
    is_active: true,
    gdpr_consent: true,
    gdpr_consent_at: '2025-04-01T10:00:00Z',
    created_at: '2025-04-01T10:00:00Z',
  },
]

export const seedMessages: SeedMessage[] = [
  {
    id: 'msg-001',
    sender_id: 'user-producer-001',
    receiver_id: 'user-consumer-001',
    content: 'Bonjour ! Merci pour votre commande de panier légumes. 🥬',
    is_read: true,
    sent_at: '2025-04-10T14:30:00Z',
    first_name: 'Marie',
    last_name: 'Martin',
  },
  {
    id: 'msg-002',
    sender_id: 'user-consumer-001',
    receiver_id: 'user-producer-001',
    content: 'Bonjour ! Hâte de recevoir ça. Petite question sur le contenu ?',
    is_read: true,
    sent_at: '2025-04-10T14:35:00Z',
    first_name: 'Jean',
    last_name: 'Dupont',
  },
  {
    id: 'msg-003',
    sender_id: 'user-producer-001',
    receiver_id: 'user-consumer-001',
    content: 'Bien sûr ! Voici ce que nous avons récolté ce matin.',
    is_read: false,
    sent_at: '2025-04-10T14:40:00Z',
    first_name: 'Marie',
    last_name: 'Martin',
  },
]
